import Header from './components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next JS Blog Site',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, hero }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
          <div className='container mx-auto p-5'>
            {hero}
            {children}
          </div>
        <Footer/>
      </body>
    </html>
  )
}
